### ISSUE TITLE
Not working under host network mode

### ISSUE THREAD

**Issue by ganganray** [limmer55/streamdock#15]
Thank you for this project. I just find that it does not work with the following compose file. I need the host mode to have easier access to ipv6.

```yaml
services:
  streamdock:
    image: ghcr.io/limmer55/streamdock:stable
    container_name: streamdock
    network_mode: host
    restart: unless-stopped
```

**Comment by roadfox** [comment]
works for me

```
services:
  streamdock:
    container_name: streamdock
    environment:
      - M3U_URL=https://iptv-org.github.io/iptv/index.m3u
    image: ghcr.io/limmer55/streamdock:stable
    ports:
      - target: 6050
        published: "6050"
        protocol: tcp
    restart: unless-stopped
    volumes: []
    devices: []
    cap_add: []
    network_mode: host
    privileged: false
```
